version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-admin-server
    network_mode: "host"  # 使用宿主机网络模式
    environment:
      NODE_ENV: production
      # Pass environment variables to the container
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  admin-vue3:
    build:
      context: ./admin-vue3
      dockerfile: Dockerfile
    container_name: nest-admin-vue3
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - server
    networks:
      - nest-admin-net

networks:
  nest-admin-net:
    driver: bridge
